"""initial users vehicles api_keys import_jobs

Revision ID: 19b7a8e43223
Revises: 
Create Date: 2026-08-13 21:02:38.523773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b7a8e43223'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('saved_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('rejected_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_type', sa.String(length=32), nullable=False),
    sa.Column('site_id', sa.String(length=128), nullable=False),
    sa.Column('car_no', sa.String(length=32), nullable=True),
    sa.Column('car_year', sa.String(length=64), nullable=True),
    sa.Column('car_km', sa.Integer(), nullable=True),
    sa.Column('car_price', sa.Integer(), nullable=True),
    sa.Column('car_maker', sa.String(length=64), nullable=True),
    sa.Column('car_model', sa.String(length=128), nullable=True),
    sa.Column('car_submodel', sa.String(length=128), nullable=True),
    sa.Column('car_grade', sa.String(length=128), nullable=True),
    sa.Column('car_subgrade', sa.String(length=128), nullable=True),
    sa.Column('car_fuel', sa.String(length=32), nullable=True),
    sa.Column('car_mission', sa.String(length=32), nullable=True),
    sa.Column('car_color', sa.String(length=32), nullable=True),
    sa.Column('car_location', sa.String(length=64), nullable=True),
    sa.Column('car_import_yn', sa.String(length=8), nullable=True),
    sa.Column('car_cc', sa.String(length=32), nullable=True),
    sa.Column('car_type', sa.String(length=64), nullable=True),
    sa.Column('car_seat', sa.String(length=32), nullable=True),
    sa.Column('detail_info', sa.Text(), nullable=True),
    sa.Column('option_info', sa.Text(), nullable=True),
    sa.Column('diag_info', sa.Text(), nullable=True),
    sa.Column('url_link', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_type', 'site_id', name='uq_vehicle_site')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('ix_vehicle_car_no', ['car_no'], unique=False)
        batch_op.create_index('ix_vehicle_maker_model', ['car_maker', 'car_model'], unique=False)
        batch_op.create_index('ix_vehicle_price', ['car_price'], unique=False)
        batch_op.create_index('ix_vehicle_scraped_at', ['scraped_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index('ix_vehicle_scraped_at')
        batch_op.drop_index('ix_vehicle_price')
        batch_op.drop_index('ix_vehicle_maker_model')
        batch_op.drop_index('ix_vehicle_car_no')

    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('import_jobs')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
